name: Package Application with Pyinstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  
  build-windows:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: .

    - uses: actions/upload-artifact@v2
      with:
        name: log4j-finder-windows
        path: dist/windows

  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-linux@main
      with:
        path: src

    - uses: actions/upload-artifact@v2
      with:
        name: log4j-finder-linux
        path: dist/linux

  build-debian8:
    runs-on: debian-8

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-linux@main
      with:
        path: src

    - uses: actions/upload-artifact@v2
      with:
        name: log4j-finder-debian8
        path: dist/linux
